package view;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import primitivas.Primitivas;
import util.JPanelGraphics;

public class FormPrincipal extends javax.swing.JFrame {

    private final Primitivas prm;
    int x1, y1;
      
    public FormPrincipal() {
        initComponents();
        formulario();
   
        pn.setPreferredSize(pn.getSize());
        
        prm = new Primitivas(pn.getPreferredSize());
        pn.add(prm);
        
        this.setLocationRelativeTo(null);
        //this.setResizable(false);
        this.setTitle("ComputaÃ§Ã£o GrÃ¡fica");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnFormasBásicas = new javax.swing.JPanel();
        rdbLapis = new javax.swing.JRadioButton();
        rdbLinha = new javax.swing.JRadioButton();
        rdbCurva = new javax.swing.JRadioButton();
        rdbElipse = new javax.swing.JRadioButton();
        rdbRetangulo = new javax.swing.JRadioButton();
        rdbPoligono = new javax.swing.JRadioButton();
        lblLapis = new javax.swing.JLabel();
        lblLinha = new javax.swing.JLabel();
        lblCurva = new javax.swing.JLabel();
        lblElipse = new javax.swing.JLabel();
        lblRetangulo = new javax.swing.JLabel();
        lblPoligono = new javax.swing.JLabel();
        pnFerramentas = new javax.swing.JPanel();
        rdbBorracha = new javax.swing.JRadioButton();
        lblBorracha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnFormasAvançadas = new javax.swing.JPanel();
        rdbTriangulo = new javax.swing.JRadioButton();
        rdbLosango = new javax.swing.JRadioButton();
        rdbCima = new javax.swing.JRadioButton();
        rdbDireita = new javax.swing.JRadioButton();
        lblTriangulo = new javax.swing.JLabel();
        lblDireita = new javax.swing.JLabel();
        lblLosango = new javax.swing.JLabel();
        lblCima = new javax.swing.JLabel();
        rdbHexagono = new javax.swing.JRadioButton();
        rdbPentagono = new javax.swing.JRadioButton();
        lblPentagono = new javax.swing.JLabel();
        lblHexagono = new javax.swing.JLabel();
        rdbEstrela4 = new javax.swing.JRadioButton();
        rdbEstrela5 = new javax.swing.JRadioButton();
        rdbCarro = new javax.swing.JRadioButton();
        rdbCasa = new javax.swing.JRadioButton();
        lblEstrela4 = new javax.swing.JLabel();
        lblEstrela5 = new javax.swing.JLabel();
        lblCarro = new javax.swing.JLabel();
        lblCasa = new javax.swing.JLabel();
        rdbG = new javax.swing.JRadioButton();
        lblG = new javax.swing.JLabel();
        rdbC = new javax.swing.JRadioButton();
        lblC = new javax.swing.JLabel();
        pnSobre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pn = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rdbLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbLinhaActionPerformed(evt);
            }
        });

        lblLapis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/lapis.png"))); // NOI18N

        lblLinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/linha.png"))); // NOI18N

        lblCurva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/curva.png"))); // NOI18N

        lblElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/ellipse.png"))); // NOI18N

        lblRetangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/quadrado.png"))); // NOI18N

        lblPoligono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/hexagon.png"))); // NOI18N

        javax.swing.GroupLayout pnFormasBásicasLayout = new javax.swing.GroupLayout(pnFormasBásicas);
        pnFormasBásicas.setLayout(pnFormasBásicasLayout);
        pnFormasBásicasLayout.setHorizontalGroup(
            pnFormasBásicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormasBásicasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnFormasBásicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdbLapis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnFormasBásicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLapis)
                    .addComponent(lblLinha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnFormasBásicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdbCurva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbElipse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnFormasBásicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurva)
                    .addComponent(lblElipse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnFormasBásicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnFormasBásicasLayout.createSequentialGroup()
                        .addComponent(rdbPoligono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPoligono))
                    .addGroup(pnFormasBásicasLayout.createSequentialGroup()
                        .addComponent(rdbRetangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRetangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(571, Short.MAX_VALUE))
        );

        pnFormasBásicasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCurva, lblElipse, lblLapis, lblLinha, lblPoligono, rdbCurva, rdbElipse, rdbLapis, rdbLinha, rdbPoligono, rdbRetangulo});

        pnFormasBásicasLayout.setVerticalGroup(
            pnFormasBásicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormasBásicasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFormasBásicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbRetangulo)
                    .addGroup(pnFormasBásicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbCurva)
                        .addComponent(rdbLapis)
                        .addComponent(lblLapis)
                        .addComponent(lblCurva))
                    .addComponent(lblRetangulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnFormasBásicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbPoligono)
                    .addGroup(pnFormasBásicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbElipse)
                        .addComponent(lblLinha)
                        .addComponent(lblElipse))
                    .addComponent(rdbLinha)
                    .addComponent(lblPoligono))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnFormasBásicasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCurva, lblElipse, lblLapis, lblLinha, lblPoligono, lblRetangulo, rdbCurva, rdbElipse, rdbLapis, rdbLinha, rdbPoligono, rdbRetangulo});

        jTabbedPane1.addTab("Forma Básicas", pnFormasBásicas);

        lblBorracha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/borracha.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/Salvar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/upload-32.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFerramentasLayout = new javax.swing.GroupLayout(pnFerramentas);
        pnFerramentas.setLayout(pnFerramentasLayout);
        pnFerramentasLayout.setHorizontalGroup(
            pnFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFerramentasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rdbBorracha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBorracha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(576, Short.MAX_VALUE))
        );
        pnFerramentasLayout.setVerticalGroup(
            pnFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(rdbBorracha)
                    .addComponent(lblBorracha))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ferramentas", pnFerramentas);

        rdbLosango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbLosangoActionPerformed(evt);
            }
        });

        lblTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/triangulo.png"))); // NOI18N

        lblDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/direita.png"))); // NOI18N

        lblLosango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/losangulo.png"))); // NOI18N

        lblCima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/cima.png"))); // NOI18N

        lblPentagono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/pentagono.png"))); // NOI18N

        lblHexagono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/hexagon.png"))); // NOI18N

        rdbCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCarroActionPerformed(evt);
            }
        });

        lblEstrela4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/estrela 4 pontos.png"))); // NOI18N

        lblEstrela5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/estrela 5 pontos.png"))); // NOI18N

        lblCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/carro.png"))); // NOI18N

        lblCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/casa.png"))); // NOI18N

        lblG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/G.png"))); // NOI18N

        lblC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/c.png"))); // NOI18N

        javax.swing.GroupLayout pnFormasAvançadasLayout = new javax.swing.GroupLayout(pnFormasAvançadas);
        pnFormasAvançadas.setLayout(pnFormasAvançadasLayout);
        pnFormasAvançadasLayout.setHorizontalGroup(
            pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormasAvançadasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                        .addComponent(rdbDireita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDireita))
                    .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                        .addComponent(rdbTriangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTriangulo)))
                .addGap(18, 18, 18)
                .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                        .addComponent(rdbLosango)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLosango)
                        .addGap(18, 18, 18)
                        .addComponent(rdbPentagono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPentagono))
                    .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                        .addComponent(rdbCima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCima)
                        .addGap(18, 18, 18)
                        .addComponent(rdbHexagono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHexagono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                        .addComponent(rdbEstrela4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstrela4)
                        .addGap(18, 18, 18)
                        .addComponent(rdbCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCarro))
                    .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                        .addComponent(rdbEstrela5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstrela5)
                        .addGap(18, 18, 18)
                        .addComponent(rdbCasa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCasa)))
                .addGap(20, 20, 20)
                .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                        .addComponent(rdbG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                        .addComponent(rdbC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblC, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(342, 342, 342))
        );

        pnFormasAvançadasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCarro, lblCasa, lblCima, lblDireita, lblEstrela4, lblEstrela5, lblHexagono, lblLosango, lblPentagono, lblTriangulo, rdbCarro, rdbCasa, rdbCima, rdbDireita, rdbEstrela4, rdbEstrela5, rdbHexagono, rdbLosango, rdbPentagono, rdbTriangulo});

        pnFormasAvançadasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblC, rdbC});

        pnFormasAvançadasLayout.setVerticalGroup(
            pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormasAvançadasLayout.createSequentialGroup()
                        .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbPentagono)
                            .addComponent(lblPentagono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDireita))
                    .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                        .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnFormasAvançadasLayout.createSequentialGroup()
                                    .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rdbCarro)
                                        .addComponent(lblCarro)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblG)
                                            .addComponent(rdbG)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rdbCasa)
                                        .addComponent(lblCasa)
                                        .addComponent(rdbC)
                                        .addComponent(lblC)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnFormasAvançadasLayout.createSequentialGroup()
                                    .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rdbEstrela4)
                                        .addComponent(lblEstrela4))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEstrela5)
                                        .addComponent(rdbEstrela5))))
                            .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                                .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdbTriangulo)
                                            .addGroup(pnFormasAvançadasLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(lblTriangulo)))
                                        .addComponent(rdbLosango))
                                    .addComponent(lblLosango))
                                .addGap(18, 18, 18)
                                .addGroup(pnFormasAvançadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCima)
                                    .addComponent(rdbDireita)
                                    .addComponent(rdbCima)
                                    .addComponent(rdbHexagono)
                                    .addComponent(lblHexagono))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnFormasAvançadasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblC, lblCarro, lblCasa, lblCima, lblDireita, lblEstrela4, lblEstrela5, lblG, lblHexagono, lblLosango, lblPentagono, lblTriangulo, rdbC, rdbCarro, rdbCasa, rdbCima, rdbDireita, rdbEstrela4, rdbEstrela5, rdbG, rdbHexagono, rdbLosango, rdbPentagono, rdbTriangulo});

        jTabbedPane1.addTab("Forma Avançadas", pnFormasAvançadas);

        jLabel1.setText("Desenvolvido por: ");

        jLabel3.setText("Guilherme Macrini Godencio [guilhermegodencio@gmail.com]");

        jLabel4.setText("Caio Oliveira [caiossoliveira@gmail.com]");

        javax.swing.GroupLayout pnSobreLayout = new javax.swing.GroupLayout(pnSobre);
        pnSobre.setLayout(pnSobreLayout);
        pnSobreLayout.setHorizontalGroup(
            pnSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSobreLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        pnSobreLayout.setVerticalGroup(
            pnSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sobre", pnSobre);

        pn.setBackground(new java.awt.Color(255, 255, 255));
        pn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnMouseDragged(evt);
            }
        });
        pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbLinhaActionPerformed

    private void rdbLosangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbLosangoActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_rdbLosangoActionPerformed

    private void pnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMousePressed
                
        prm.backup();
        
        x1 = evt.getX();
        y1 = evt.getY();
        
    }//GEN-LAST:event_pnMousePressed

    private void pnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMouseDragged
        
        if (rdbLapis.isSelected() ){
            int x = evt.getX();
            int y = evt.getY();
            prm.lapis(x, y);
            repaint();
        }
       
       else if(rdbLinha.isSelected()){
            
            int x2 = evt.getX();
            int y2 = evt.getY();

            prm.linha(x1, y1, x2, y2); 
       }      
       
       else if(rdbElipse.isSelected()){
           
           int x2 = evt.getX();
           int y2 = evt.getY();
           
           prm.Elipse(x1, y1, x2, y2);  
       }
       
       else if(rdbRetangulo.isSelected()){
           
           int x2 = evt.getX();
           int y2 = evt.getY();
           
           prm.Retangulo(x1, y1, x2, y2);
       }
       
       else if(rdbTriangulo.isSelected()){
           
           int x2 = evt.getX();
           int y2 = evt.getY();
           
           prm.Triangulo(x1, y1, x2, y2);
       }
       
       else if(rdbPentagono.isSelected()){
           
           int x2 = evt.getX();
           int y2 = evt.getY();
           
           prm.Pentagono(x1, y1, x2, y2);
       }
       
       else if(rdbLosango.isSelected()){
           
           int x2 = evt.getX();
           int y2 = evt.getY();
           
           prm.Losango(x1, y1, x2, y2);
       }
       
       else if(rdbCima.isSelected()){
           
           int x2 = evt.getX();
           int y2 = evt.getY();
           
           prm.SetaVertical(x1, y1, x2, y2);
       }
       
       else if(rdbDireita.isSelected()){
           
           int x2 = evt.getX();
           int y2 = evt.getY();
           
           prm.SetaHorizontal(x1, y1, x2, y2);
       }
       
       else if(rdbHexagono.isSelected()){
           
           int x2 = evt.getX();
           int y2 = evt.getY();
           
           prm.Hexagono(x1, y1, x2, y2);
       }
       
       else if(rdbBorracha.isSelected()){
           
           int x2 = evt.getX();
           int y2 = evt.getY();
           
           prm.Borracha(x1, y1, x2, y2);
       }
       
        else if(rdbEstrela4.isSelected()){
           
           int x2 = evt.getX();
           int y2 = evt.getY();
           
           prm.Estrela4(x1, y1, x2, y2);
       }
        
        else if(rdbEstrela5.isSelected()){
           
           int x2 = evt.getX();
           int y2 = evt.getY();
           
           prm.Estrela5(x1, y1, x2, y2);
       }
       
        else if(rdbG.isSelected()){
            int x2 = evt.getX();
            int y2 = evt.getY();
            
            prm.LetraG(x1, y1, x2, y2);
        }
       
         else if(rdbC.isSelected()){
            int x2 = evt.getX();
            int y2 = evt.getY();
            
            prm.LetraC(x1, y1, x2, y2);
        }
       
        else if(rdbCasa.isSelected()){
            int x2 = evt.getX();
            int y2 = evt.getY();
            
            prm.Casa(x1, y1, x2, y2);
        } else if(rdbCarro.isSelected()){
            int x2 = evt.getX();
            int y2 = evt.getY();
            
            prm.Carro(x1, y1, x2, y2);
        }
       
    }//GEN-LAST:event_pnMouseDragged

    private void rdbCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCarroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
        BufferedImage img =
                new BufferedImage(pn.getWidth(), pn.getHeight(), BufferedImage.TYPE_INT_RGB);
        img = prm.image;
        
        if(img == null){
            img = new BufferedImage(pn.getWidth(), pn.getHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics2D g = img.createGraphics();
            g.setColor(Color.WHITE);
            g.fillRect(0, 0, pn.getWidth(), pn.getHeight());
        }
        
        JFileChooser jf = new JFileChooser();
        jf.setDialogTitle("Salvar");
        jf.setDialogType(JFileChooser.SAVE_DIALOG);
        
        FileNameExtensionFilter ff = new FileNameExtensionFilter("png (*.png)", "png");
        FileNameExtensionFilter ff1 = new FileNameExtensionFilter("bmp (*.bmp)", "bmp");
        jf.setFileFilter(ff);
        jf.setFileFilter(ff1);
        
        
        int res = jf.showSaveDialog(this);
        if(res == JFileChooser.APPROVE_OPTION){
            try {
                //Pega a descrição do tipo de arquivo que se deseja salvar
                String aux = jf.getFileFilter().getDescription();
                int posInicial = aux.indexOf("(");
                posInicial = posInicial+3;
                int posFinal = aux.indexOf(")");
                String ext = aux.substring(posInicial, posFinal);
                
                //caso o usuário informe um formato diferente do selecionado 
                //salvará no formato que o usuário digitou
                String nome = jf.getSelectedFile().toString();
                int v = nome.lastIndexOf(".");
                v++;
                aux = new String();
                aux = nome.substring(v, nome.length());
                if(aux != null){
                    if((aux.compareToIgnoreCase("bmp")) == 0 || (aux.compareToIgnoreCase("png")) == 0){
                        ext = aux;
                    }
                }
                //Salva o arquivo
                String caminho = jf.getSelectedFile().getAbsolutePath() +"."+ext ;
                File f = new File(caminho);
                
                ImageIO.write(img, ext, f);
                
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Erro: " +ex);
            }
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
            JFileChooser jf = new JFileChooser();
            jf.setDialogTitle("Abrir");
            jf.setDialogType(JFileChooser.OPEN_DIALOG);

            //O usuário pode selecionar somente arquivos e não diretórios
            jf.setFileSelectionMode(JFileChooser.FILES_ONLY);

            //Habilita seleção única de arquivos
            jf.setMultiSelectionEnabled(false);
            
            FileNameExtensionFilter ff = new FileNameExtensionFilter("png (*.png)", "png");
            FileNameExtensionFilter ff1 = new FileNameExtensionFilter("bmp (*.bmp)", "bmp");
            jf.setFileFilter(ff);
            jf.setFileFilter(ff1);

            int res = jf.showOpenDialog(this);
            if(res == JFileChooser.APPROVE_OPTION){
                //Arquivo Selecionado
                File f = jf.getSelectedFile();
                BufferedImage imagem = ImageIO.read(f);;
                prm.image = imagem;
                prm.repaint();
                
            }
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBorracha;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCarro;
    private javax.swing.JLabel lblCasa;
    private javax.swing.JLabel lblCima;
    private javax.swing.JLabel lblCurva;
    private javax.swing.JLabel lblDireita;
    private javax.swing.JLabel lblElipse;
    private javax.swing.JLabel lblEstrela4;
    private javax.swing.JLabel lblEstrela5;
    private javax.swing.JLabel lblG;
    private javax.swing.JLabel lblHexagono;
    private javax.swing.JLabel lblLapis;
    private javax.swing.JLabel lblLinha;
    private javax.swing.JLabel lblLosango;
    private javax.swing.JLabel lblPentagono;
    private javax.swing.JLabel lblPoligono;
    private javax.swing.JLabel lblRetangulo;
    private javax.swing.JLabel lblTriangulo;
    private javax.swing.JPanel pn;
    private javax.swing.JPanel pnFerramentas;
    private javax.swing.JPanel pnFormasAvançadas;
    private javax.swing.JPanel pnFormasBásicas;
    private javax.swing.JPanel pnSobre;
    private javax.swing.JRadioButton rdbBorracha;
    private javax.swing.JRadioButton rdbC;
    private javax.swing.JRadioButton rdbCarro;
    private javax.swing.JRadioButton rdbCasa;
    private javax.swing.JRadioButton rdbCima;
    private javax.swing.JRadioButton rdbCurva;
    private javax.swing.JRadioButton rdbDireita;
    private javax.swing.JRadioButton rdbElipse;
    private javax.swing.JRadioButton rdbEstrela4;
    private javax.swing.JRadioButton rdbEstrela5;
    private javax.swing.JRadioButton rdbG;
    private javax.swing.JRadioButton rdbHexagono;
    private javax.swing.JRadioButton rdbLapis;
    private javax.swing.JRadioButton rdbLinha;
    private javax.swing.JRadioButton rdbLosango;
    private javax.swing.JRadioButton rdbPentagono;
    private javax.swing.JRadioButton rdbPoligono;
    private javax.swing.JRadioButton rdbRetangulo;
    private javax.swing.JRadioButton rdbTriangulo;
    // End of variables declaration//GEN-END:variables

void formulario(){

ButtonGroup bg = new ButtonGroup();

//formas básicas
bg.add(rdbLapis);
bg.add(rdbLinha);
bg.add(rdbCurva);
bg.add(rdbElipse);
bg.add(rdbRetangulo);
bg.add(rdbPoligono);

//formas avançadas
bg.add(rdbTriangulo);
bg.add(rdbLosango);
bg.add(rdbPentagono);
bg.add(rdbHexagono);
bg.add(rdbCima);
bg.add(rdbDireita);
bg.add(rdbCarro);
bg.add(rdbCasa);
bg.add(rdbEstrela4);
bg.add(rdbEstrela5);
bg.add(rdbG);
bg.add(rdbC);
bg.add(rdbBorracha);
    }
}
